CREATE TABLE Account(
	userName VARCHAR(100) PRIMARY KEY,
	[password] VARCHAR(100) NOT NULL,
	fullName NVARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(20) NOT NULL,
	birthDate DATE NOT NULL,
	[role] VARCHAR(20) DEFAULT 'USER',
	avatar VARBINARY(MAX) NOT NULL,
)

CREATE TABLE Post(
	postId INT IDENTITY(1,1) PRIMARY KEY,
	userName VARCHAR(100) NOT NULL,
	[status] VARCHAR(20) DEFAULT 'PENDING',
	privacy VARCHAR(20) NOT NULL,
	header NVARCHAR(100) NOT NULL,
	content NVARCHAR(MAX) NOT NULL,
	postTime DATETIME DEFAULT GETDATE(),
)